server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MyShop?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: 123123
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true